### PR TITLE
Added a slider for changing minimum post score, and added /r/CommercialCuts.

### PR DESCRIPTION
**Pull request by williambl**

### CODE REVIEW

**Comment by topotech** [comment]
Can you modify it in a way the "past shows" section appears in the menu? I don't have as much spare time as I did back then so I can't do it myself. If you can do that I'll willingly merge your modifications. The scrollbar was a great idea by the way!

**Comment by williambl** [comment]
A scroll bar now should automatically appear when the menu gets too big.

**Comment by williambl** [comment]
@topotech Is this mergeable now?

**Comment by topotech** [comment]
YES! you are awesome ;-) Consider your pull request merged

**Comment by williambl** [comment]
Thanks!

**Pull request merged**
